### ISSUE TITLE
Accessing posts by tag

### ISSUE THREAD

**Issue by rdricco** [conradj/gatsby-source-pocket#1]
Hi, is it possible to filter posts by tag? 
My idea is to share only one tag from my pocket account, something like "pocket-linklog", and keep the remaining items on private.

**Comment by conradj** [comment]
@rdricco I've been meaning to do this. I'll get it in shortly.

**Comment by conradj** [comment]
Fixed in https://github.com/conradj/gatsby-source-pocket/commit/8f2a56e3f5cb7c0a1b871413b05af2dfa5070e1e

**Comment by conradj** [comment]
@rdricco give me a shout and let me know how you get on

**Comment by rdricco** [comment]
Cool, I will give a try soon as possible.
