### ISSUE TITLE
Rate limit clarification

### ISSUE THREAD

**Issue by Vacilando** [conradj/gatsby-source-pocket#14]
According to https://getpocket.com/developer/docs/rate-limits 
- "Each user is limited to 320 calls per hour"
- Each application is limited to 10,000 calls per hour

It's not clear how does this translate when using this plugin. 
Gatsby builds a site at once, meaning a burst of calls to the Pocket API.

Does each record in Pocket need one call to retrieve? If so, can we get max 320 or 10k records only?
Or is the plugin getting them in batches, so it requires less calls?
What's the maximum size of Pocket API collection of links that can be retrieved using this module / Gatsby?

**Comment by conradj** [comment]
The plugin will go and get all records matching the `options` in `gatsby-config.js`, in **one** call. I have a nightly scheduled build to get the current week's articles (1 call). My weekly scheduled build makes 52 calls, to get a years worth of data batched by week.
