### ISSUE TITLE
Filter by tagged items?

### ISSUE THREAD

**Issue by Vacilando** [conradj/gatsby-source-pocket#15]
It's possible to use value "_untagged_" in tagFilter  to get all items that are not tagged yet.

Is it possible to do the opposite - get all items that are tagged?
Perhaps by negating the condition, something like "NOT _untagged_"?

**Comment by conradj** [comment]
It doesn't look like this is an option in the [Pocket API](https://getpocket.com/developer/docs/v3/retrieve) so you would need to do this after retrieval.
