### ISSUE TITLE
Support Gatsby v4

### ISSUE THREAD

**Issue by Vacilando** [conradj/gatsby-source-pocket#17]
There seems to be a new version that supports Gatsby v4 - @raqystyle  / @conradj could you please also publish it via npm? 

https://www.npmjs.com/package/gatsby-source-pocket is currently still the old one.

**Comment by conradj** [comment]
Hey @Vacilando I've published @raqystyle's changes to npm, could you give it a go please?

**Comment by Vacilando** [comment]
@conradj / @raqystyle unfortunately, there's the following error showing up during develop:

> "gatsby-source-pocket" threw an error while running the sourceNodes lifecycle:
> RangeError: Invalid time value

<img width="473" alt="image" src="https://user-images.githubusercontent.com/147258/143942319-c7257b35-fada-4a62-998a-56034994cb00.png">0

This exception occurs when the Date object contains an invalid date - see https://stackoverflow.com/questions/54462227/rangeerror-invalid-time-value/54462335#54462335

Could you please have a look at that?

**Comment by Vacilando** [comment]
Could you reopen this ticket, please?

**Comment by Vacilando** [comment]
Created a new ticket for this -> https://github.com/conradj/gatsby-source-pocket/issues/18
