### ISSUE TITLE
Add `readDay` field

### ISSUE THREAD

**Issue by mAAdhaTTah** [conradj/gatsby-source-pocket#4]
I use Pocket pretty extensively, and would like to group my read links by day, rather than by week. Doing so manually would be tedious, but if the Pocket source exposed `readDay` (similar to `readWeek`) I could group that really easily. Would you be willing to add this?

**Comment by conradj** [comment]
@mAAdhaTTah should be no problem, will get it in as soon as I have a moment :-) 

Or you can submit a PR to make sure it does what you want it to?

Out of interest, do you have a site that uses this plugin? I'd really like to see how others are using it!

**Comment by mAAdhaTTah** [comment]
I'm still working on it, but I've got an initial version up here: https://reads.jamesdigioia.com/

Not really in love with the design, but I basically mirrored what I have on my main site so I could get something up quick. You can see the source here: https://github.com/mAAdhaTTah/jamesdigioia.com

Note that this pulls in data from both Pocket as well as a WordPress site I'm storing my links on, so there's some data merging logic going on there as well.

**Comment by conradj** [comment]
@mAAdhaTTah I've added this field in now. Hope it helps 🙂

**Comment by mAAdhaTTah** [comment]
Great, thank you! Will update my site with it.
