### ISSUE TITLE
Multiple sources

### ISSUE THREAD

**Issue by ChrisChinchilla** [conradj/gatsby-source-pocket#5]
Hello, nice source plugin, but I have a particular use case that I'm not is possible or not, and I am newish to Gatsby, so bear with me.

I want to create pages  based on different Pocket tag filters, but the Pocket API doesn't return the tag in the response. So I tried creating multiple instances of the plugin with different tag filters defined in Gatsby config, and that works, but now I'm not sure how to detect the difference between those sources anywhere else in Gatsby. If that makes any sense at all, I'd love to know if you think that's possible.

**Comment by conradj** [comment]
Hi @ChrisChinchilla, sorry for the delay in replying! 

The pocket api should [return the tags](https://getpocket.com/developer/docs/v3/retrieve) (see the list of returned fields at the bottom of the page, noting that their example doesn't include all fields 🙄), and it should be possible to [query these](https://github.com/conradj/gatsby-source-pocket#how-to-query-your-pocket-articles-data-using-graphql) to create tags based on pages. I might have misunderstood  what you want to do though, in which case please reopen.
