### ISSUE TITLE
Expose Pocket tags in GraphQL

### ISSUE THREAD

**Issue by nakleiderer** [conradj/gatsby-source-pocket#6]
According to the [Pocket API docs](https://getpocket.com/developer/docs/v3/retrieve), the tags associated with an article are returned. However, I cannot query field `tags` on type `PocketArticle`. Could we expose the tags returned by the Pocket API in GraphQL?

**Comment by conradj** [comment]
I've no idea why I missed this one out, thanks for looking at it! Out of interest, do you have a site that uses this plugin that I can see?

**Comment by nakleiderer** [comment]
@conradj Yes, it's a personal website that I'm making as a hobby project to explore Gatsby. It's a private repository right now, but I am glad to add you as a collaborator so you can see it. Look for your invite soon :)
